/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useThree } from '@react-three/fiber'
// import { useGesture } from '@use-gesture/react'

export default function Model(props) {
  const group = useRef()
  const { size, viewport } = useThree()
  // const aspect = size.width / viewport.width

  const { nodes, materials } = useGLTF('/minecraft_diamond-pickaxe.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          position={[0, -5, 0]}
          scale={[0.11, 0.11, 0.11]}
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={materials['Material.009']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/minecraft_diamond-pickaxe.glb')
