/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DragControls } from 'three/examples/jsm/controls/DragControls'
import { useThree, extend } from '@react-three/fiber'

extend({ DragControls })

export default function Model(props) {
  const group = useRef()
  console.log(group)
  const {
    camera,
    gl: { domElement },
  } = useThree()

  const { scene } = useGLTF('/minecraft_diamond-pickaxe.glb')

  return (
    <>
      <primitive object={scene} scale={[0.1, 0.1, 0.1]} />
      <dragControls args={[[scene], camera, domElement]} />
    </>
  )
}

useGLTF.preload('/minecraft_diamond-pickaxe.glb')
